<a href="https://colab.research.google.com/github/spegas/Dacon/blob/main/Get_Stock_Data_Naver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install finance-datareader

In [2]:
!pip install wget

  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9672 sha256=391972f710bff31c8f7fe0d59cde9232445a27a6e792db263f7fa7c71db53c15
  Stored in directory: /root/.cache/pip/wheels/a1/b6/7c/0e63e34eb06634181c63adacca38b79ff8f35c37e3c13e3c02
Successfully built wget


In [3]:
import pandas as pd
import numpy as np
import os
import FinanceDataReader as fdr
import wget

from zipfile import ZipFile
from os.path import basename

In [4]:
if not os.path.isdir("base"):
  print("base 디렉토리 생성")
  os.makedirs("base")

if not os.path.isdir("price"):
  print("price 디렉토리 생성")
  os.makedirs("price")

base 디렉토리 생성
price 디렉토리 생성


In [5]:
stock_list_file_url = "https://raw.githubusercontent.com/spegas/Dacon/main/stock_list.csv"
if os.path.exists('base/stock_list.csv'):
  os.remove('base/stock_list.csv')
  print('이전에 저장된 주식 종목 리스트 파일을 삭제 합니다.')
wget.download(stock_list_file_url, 'base/stock_list.csv')
print('주식 종목 리스트 파일 다운로드 완료')

주식 종목 리스트 파일 다운로드 완료


In [6]:
stock_list_name = 'base/stock_list.csv'
pd_stock_list = pd.read_csv(stock_list_name)
pd_stock_list['종목코드'] = pd_stock_list['종목코드'].apply(lambda x : str(x).zfill(6))
pd_stock_list.head(10)

종목명    종목코드   상장시장
0      삼성전자  005930  KOSPI
1    SK하이닉스  000660  KOSPI
2     NAVER  035420  KOSPI
3       카카오  035720  KOSPI
4  삼성바이오로직스  207940  KOSPI
5     삼성전자우  005935  KOSPI
6      LG화학  051910  KOSPI
7     삼성SDI  006400  KOSPI
8       현대차  005380  KOSPI
9      셀트리온  068270  KOSPI

In [7]:
start_date = '20200101'
end_date = '20211125'

In [8]:
for f_index in range(0, pd_stock_list.shape[0]):
  f_code = pd_stock_list.iloc[f_index]['종목코드']
  f_name = pd_stock_list.iloc[f_index]['종목명']
  price_filename = str('price/') + str(f_code) + str('_price.csv')
  if not os.path.exists(price_filename):
    f_price = fdr.DataReader(f_code, start = start_date, end = end_date)
    f_price.to_csv(price_filename)
    print('[종목코드 : %s, 종목명 : %s] 가격 정보 저장 완료' % (str(f_code), str(f_name)))
  else:
    print('[종목코드 : %s, 종목명 : %s] 가격 정보 파일 존재' % (str(f_code), str(f_name)))

[종목코드 : 005930, 종목명 : 삼성전자] 가격 정보 저장 완료
[종목코드 : 000660, 종목명 : SK하이닉스] 가격 정보 저장 완료
[종목코드 : 035420, 종목명 : NAVER] 가격 정보 저장 완료
[종목코드 : 035720, 종목명 : 카카오] 가격 정보 저장 완료
[종목코드 : 207940, 종목명 : 삼성바이오로직스] 가격 정보 저장 완료
[종목코드 : 005935, 종목명 : 삼성전자우] 가격 정보 저장 완료
[종목코드 : 051910, 종목명 : LG화학] 가격 정보 저장 완료
[종목코드 : 006400, 종목명 : 삼성SDI] 가격 정보 저장 완료
[종목코드 : 005380, 종목명 : 현대차] 가격 정보 저장 완료
[종목코드 : 068270, 종목명 : 셀트리온] 가격 정보 저장 완료
[종목코드 : 000270, 종목명 : 기아] 가격 정보 저장 완료
[종목코드 : 005490, 종목명 : POSCO] 가격 정보 저장 완료
[종목코드 : 066570, 종목명 : LG전자] 가격 정보 저장 완료
[종목코드 : 028260, 종목명 : 삼성물산] 가격 정보 저장 완료
[종목코드 : 012330, 종목명 : 현대모비스] 가격 정보 저장 완료
[종목코드 : 096770, 종목명 : SK이노베이션] 가격 정보 저장 완료
[종목코드 : 051900, 종목명 : LG생활건강] 가격 정보 저장 완료
[종목코드 : 017670, 종목명 : SK텔레콤] 가격 정보 저장 완료
[종목코드 : 105560, 종목명 : KB금융] 가격 정보 저장 완료
[종목코드 : 055550, 종목명 : 신한지주] 가격 정보 저장 완료
[종목코드 : 034730, 종목명 : SK] 가격 정보 저장 완료
[종목코드 : 036570, 종목명 : 엔씨소프트] 가격 정보 저장 완료
[종목코드 : 011200, 종목명 : HMM] 가격 정보 저장 완료
[종목코드 : 015760, 종목명 : 한국전력] 가격 정보 저장 완료
[종목코드 : 032830, 종목명 : 삼성생명] 가

In [9]:
# Zip the files from given directory that matches the filter
def zipFilesInDir(dirName, zipFileName, filter):
   # create a ZipFile object
   with ZipFile(zipFileName, 'w') as zipObj:
       # Iterate over all the files in directory
       for folderName, subfolders, filenames in os.walk(dirName):
           for filename in filenames:
               if filter(filename):
                   # create complete filepath of file in directory
                   filePath = os.path.join(folderName, filename)
                   # Add file to zip
                   zipObj.write(filePath, basename(filePath))

In [10]:
zipFilesInDir('price', 'price2.zip', lambda name : 'csv' in name)

In [634]:
pd_price = pd.read_csv('price/000670_price.csv')

In [635]:
pd_price

Date    Open    High     Low   Close  Volume    Change
0    2020-01-02  645000  653000  632000  646000    1065  0.001550
1    2020-01-03  647000  664000  641000  658000    1431  0.018576
2    2020-01-06  647000  659000  643000  652000    1018 -0.009119
3    2020-01-07  652000  666000  647000  658000    1338  0.009202
4    2020-01-08  644000  651000  636000  644000    1336 -0.021277
..          ...     ...     ...     ...     ...     ...       ...
466  2021-11-19  648000  655000  637000  650000    2720 -0.001536
467  2021-11-22  650000  665000  643000  665000     929  0.023077
468  2021-11-23  664000  664000  650000  650000     984 -0.022556
469  2021-11-24  645000  652000  641000  647000     859 -0.004615
470  2021-11-25  645000  655000  642000  647000     554  0.000000

[471 rows x 7 columns]

In [636]:
start_date = pd_price['Date'].values[0]
end_date = pd_price['Date'].values[-1]

print(" -- start_date, end_date --")
print(start_date, end_date)

 -- start_date, end_date --
2020-01-02 2021-11-25


In [637]:
start_weekday = pd.to_datetime(start_date).weekday()
max_weeknum = pd.to_datetime(end_date).strftime('%V')
Business_days = pd.DataFrame(pd.date_range(start_date,end_date,freq='B'), columns = ['Date'])

In [638]:
print(f'WEEKDAY of "start_date" : {start_weekday}')
print(f'NUM of WEEKS to "end_date" : {max_weeknum}')
print(f'HOW MANY "Business_days" : {Business_days.shape}', )
print(Business_days.head())

WEEKDAY of "start_date" : 3
NUM of WEEKS to "end_date" : 47
HOW MANY "Business_days" : (496, 1)
        Date
0 2020-01-02
1 2020-01-03
2 2020-01-06
3 2020-01-07
4 2020-01-08


In [639]:
pd_price['weekday'] = pd_price.Date.apply(lambda x: pd.to_datetime(x).weekday())

In [640]:
# 1년치로 데이터 생성되기 때문에 이를 바로 잡아야 함.(주수는 1년만다 반복됨. 따라서 동일한 값이 2번 들어감)
#pd_total_price_data['weeknum'] = pd_total_price_data.Date.apply(lambda x: pd.to_datetime(x).strftime('%V'))

last_weeknum = 0

pd_price['weeknum'] = 0

for d_index in range(0, pd_price.shape[0]):
  now_date = pd_price['Date'].values[d_index]
  if pd.to_datetime(start_date).year == pd.to_datetime(now_date).year:
      last_weeknum = int(pd.to_datetime(now_date).strftime('%V'))
      pd_price['weeknum'].values[d_index] = last_weeknum
  else:
      pd_price['weeknum'].values[d_index] = int(last_weeknum) + int(pd.to_datetime(now_date).strftime('%V'))

In [641]:
pd_price['weekday'].values[0]

3

In [642]:
while int(pd_price['weekday'].values[0]) != 0:
  pd_price.drop(index=pd_price.index[0], axis=0, inplace=True)

pd_price = pd_price.reset_index(drop=True)

In [643]:
pd_price.head(10)

Date    Open    High     Low  ...  Volume    Change  weekday  weeknum
0  2020-01-06  647000  659000  643000  ...    1018 -0.009119        0        2
1  2020-01-07  652000  666000  647000  ...    1338  0.009202        1        2
2  2020-01-08  644000  651000  636000  ...    1336 -0.021277        2        2
3  2020-01-09  636000  659000  636000  ...    1520  0.023292        3        2
4  2020-01-10  650000  663000  645000  ...    1402 -0.004552        4        2
5  2020-01-13  647000  663000  646000  ...    1471  0.003049        0        3
6  2020-01-14  658000  664000  647000  ...    1917 -0.001520        1        3
7  2020-01-15  653000  668000  653000  ...     741  0.013699        2        3
8  2020-01-16  669000  680000  661000  ...    1222  0.021021        3        3
9  2020-01-17  677000  685000  671000  ...     974 -0.013235        4        3

[10 rows x 9 columns]

In [644]:
pd_price.shape

(469, 9)

In [645]:
pd_price['week_diff'] = 0

In [646]:
for d_index in range(0, pd_price.shape[0]-5):
  #print(d_index, (pd_price['Close'].values[d_index+5] - pd_price['Close'].values[d_index]))
  pd_price['week_diff'].values[d_index] = (pd_price['Close'].values[d_index+5] - pd_price['Close'].values[d_index])

In [647]:
def get_sma_index(pd_stock_price, period_of_list):

    for period in period_of_list:
        sma_column_name = str('SMA_') + str(period)
        pd_stock_price[sma_column_name] = pd_stock_price['Close'].rolling(window=period, min_periods=period_of_list[0]).mean()
        pd_stock_price[sma_column_name] = pd_stock_price[sma_column_name].round(2)

    print(pd_stock_price.head(10))

    return pd_stock_price

In [648]:
pd_price = get_sma_index(pd_price, [5, 10, 20, 30])

         Date    Open    High  ...     SMA_10     SMA_20     SMA_30
0  2020-01-06  647000  659000  ...        NaN        NaN        NaN
1  2020-01-07  652000  666000  ...        NaN        NaN        NaN
2  2020-01-08  644000  651000  ...        NaN        NaN        NaN
3  2020-01-09  636000  659000  ...        NaN        NaN        NaN
4  2020-01-10  650000  663000  ...  653800.00  653800.00  653800.00
5  2020-01-13  647000  663000  ...  654500.00  654500.00  654500.00
6  2020-01-14  658000  664000  ...  654857.14  654857.14  654857.14
7  2020-01-15  653000  668000  ...  656250.00  656250.00  656250.00
8  2020-01-16  669000  680000  ...  658888.89  658888.89  658888.89
9  2020-01-17  677000  685000  ...  660100.00  660100.00  660100.00

[10 rows x 14 columns]


In [649]:
def get_ema_index(pd_stock_price, period_of_list):

    for period in period_of_list:
        ema_column_name = str('EMA_') + str(period)
        pd_stock_price[ema_column_name] = pd_stock_price['Close'].rolling(window=period, min_periods=period_of_list[0]).mean()
        pd_stock_price[ema_column_name] = pd_stock_price[ema_column_name].round(2)

    print(pd_stock_price.head(10))

    return pd_stock_price

In [650]:
pd_price = get_ema_index(pd_price, [5, 10, 20, 30])

         Date    Open    High  ...     EMA_10     EMA_20     EMA_30
0  2020-01-06  647000  659000  ...        NaN        NaN        NaN
1  2020-01-07  652000  666000  ...        NaN        NaN        NaN
2  2020-01-08  644000  651000  ...        NaN        NaN        NaN
3  2020-01-09  636000  659000  ...        NaN        NaN        NaN
4  2020-01-10  650000  663000  ...  653800.00  653800.00  653800.00
5  2020-01-13  647000  663000  ...  654500.00  654500.00  654500.00
6  2020-01-14  658000  664000  ...  654857.14  654857.14  654857.14
7  2020-01-15  653000  668000  ...  656250.00  656250.00  656250.00
8  2020-01-16  669000  680000  ...  658888.89  658888.89  658888.89
9  2020-01-17  677000  685000  ...  660100.00  660100.00  660100.00

[10 rows x 18 columns]


In [651]:
def get_mfi_index(pd_stock_price, period_of_list):

    pd_stock_price['TP'] = (pd_stock_price['Close'] + pd_stock_price['High'] + pd_stock_price['Low']) / 3
    pd_stock_price['TP'] = pd_stock_price['TP'].round(2)

    pd_stock_price['PMF'] = 0
    pd_stock_price['NMF'] = 0

    # Loop through the typical price
    for i in range(0, (pd_stock_price.shape[0] - 1)):
        # 당일의 중심가격이 전일의 중심가격보다 크면 긍정적 현금흐름
        if pd_stock_price['TP'].values[i] < pd_stock_price['TP'].values[i + 1]:
            pd_stock_price['PMF'].values[i + 1] = pd_stock_price['TP'].values[i + 1] * pd_stock_price['Volume'].values[i + 1]
            pd_stock_price['NMF'].values[i + 1] = 0
        # 당일의 중심가격이 전일의 중심가격보다 작거나 같으면 부정적 현금흐름
        else:
            pd_stock_price['NMF'].values[i + 1] = pd_stock_price['TP'].values[i + 1] * pd_stock_price['Volume'].values[i + 1]
            pd_stock_price['PMF'].values[i + 1] = 0

    for period in period_of_list:
        pd_stock_price['MFR'] = pd_stock_price['PMF'].rolling(window=period, min_periods=period_of_list[0]).sum() / pd_stock_price['NMF'].rolling(
            window=period, min_periods=period_of_list[0]).sum()
        mfi_columns_name = str('MFI_') + str(period)
        pd_stock_price[mfi_columns_name] = 100 - 100 / (1 + pd_stock_price['MFR'])
        pd_stock_price[mfi_columns_name] = pd_stock_price[mfi_columns_name].round(2)

    # return pd_mfi_index
    return pd_stock_price

In [652]:
pd_price = get_mfi_index(pd_price, [5, 10, 20, 30])

In [653]:
def get_obv_index(pd_stock_price, period_of_list):

    pd_stock_price['OBV'] = 0

    # Loop through the typical price
    for i in range(1, pd_stock_price.shape[0]):
        # 다음날 가격이 상승한 경우
        if pd_stock_price.Close[i] > pd_stock_price.Close[i - 1]:
            # 현재 obv 값 = 이전 obv + 현재 Volumne 값
            pd_stock_price['OBV'].values[i] = (pd_stock_price['OBV'].values[-1] + pd_stock_price['Volume'].values[i])
        # 다음날 가격이 하락한 경우
        elif pd_stock_price.Close[i] < pd_stock_price.Close[i - 1]:
            # 현재 obv 값 = 이전 obv - 현재 Volumne 값
            pd_stock_price['OBV'].values[i] = (pd_stock_price['OBV'].values[-1] - pd_stock_price['Volume'].values[i])
        else:
            pd_stock_price['OBV'].values[i] = pd_stock_price['OBV'].values[-1]

    for period in period_of_list:
        obv_columns_name = str('OBV_') + str(period)
        pd_stock_price[obv_columns_name] = pd_stock_price['OBV'].ewm(com=period, min_periods=period_of_list[0]).mean()
        pd_stock_price[obv_columns_name] = pd_stock_price[obv_columns_name].round(2)

    return pd_stock_price

In [654]:
pd_price = get_obv_index(pd_price, [5, 10, 20, 30])

In [655]:
def get_pvt_index(pd_stock_price, period_of_list):

    pd_stock_price['PVT'] = 0

    # Loop through the typical price
    for i in range(1, pd_stock_price.shape[0]):
        pvt_value = pd_stock_price['Close'].values[i] - pd_stock_price['Close'].values[i - 1]
        pvt_value = (pvt_value / pd_stock_price['Close'].values[i - 1]) * pd_stock_price['Volume'].values[i]
        pd_stock_price['PVT'].values[i] = pvt_value + pd_stock_price['PVT'].values[-1]

    for period in period_of_list:
        pvt_columns_name = str('PVT_') + str(period)
        pd_stock_price[pvt_columns_name] = pd_stock_price['PVT'].ewm(com=period, min_periods=period_of_list[0]).mean()
        pd_stock_price[pvt_columns_name] = pd_stock_price[pvt_columns_name].round(2)

    return pd_stock_price

In [656]:
pd_price = get_pvt_index(pd_price, [5, 10, 20, 30])

In [657]:
def get_macd_index(pd_stock_price, m_NumFast=12, m_NumSlow=26, m_NumSignal=9):

    pd_stock_price['EMAFast'] = pd_stock_price['Close'].ewm(span=m_NumFast, min_periods=m_NumFast - 1).mean()
    pd_stock_price['EMASlow'] = pd_stock_price['Close'].ewm(span=m_NumSlow, min_periods=m_NumSlow - 1).mean()
    pd_stock_price['MACD'] = pd_stock_price['EMAFast'] - pd_stock_price['EMASlow']

    return pd_stock_price

In [658]:
pd_price = get_macd_index(pd_price, 12, 26, 9)

In [659]:
def get_bollinger_bands(pd_stock_price, period_of_list):

    for period in period_of_list:
        bl_ma_columns_name = str('BL_MA_') + str(period)
        pd_stock_price[bl_ma_columns_name] = pd_stock_price['Close'].ewm(com=period, min_periods=period_of_list[0]).mean()
        pd_stock_price[bl_ma_columns_name] = pd_stock_price[bl_ma_columns_name].round(2)

        bl_std_columns_name = str('BL_STD_') + str(period)
        pd_stock_price[bl_std_columns_name] = pd_stock_price['Close'].ewm(com=period, min_periods=period_of_list[0]).std()
        pd_stock_price[bl_std_columns_name] = pd_stock_price[bl_std_columns_name].round(2)

        bl_up_columns_name = str('BL_UP_') + str(period)
        pd_stock_price[bl_up_columns_name] = pd_stock_price[bl_ma_columns_name] + (2 * pd_stock_price[bl_std_columns_name])

        bl_lower_columns_name = str('BL_LO_') + str(period)
        pd_stock_price[bl_lower_columns_name] = pd_stock_price[bl_ma_columns_name] - (
                    2 * pd_stock_price[bl_std_columns_name])

    return pd_stock_price

In [660]:
pd_price = get_bollinger_bands(pd_price, [5, 10, 20, 30])

In [661]:
def get_stochastic_oscillator(pd_stock_price, period_of_list):

    for period in period_of_list:
        st_max_columns_name = str('ST_MAX_') + str(period)
        pd_stock_price[st_max_columns_name] = pd_stock_price['High'].rolling(period, min_periods=period_of_list[0]).max()

        st_min_columns_name = str('ST_MIN_') + str(period)
        pd_stock_price[st_min_columns_name] = pd_stock_price['Low'].rolling(period, min_periods=period_of_list[0]).min()

        st_k_columns_name = str('ST_K_') + str(period)
        pd_stock_price[st_k_columns_name] = (pd_stock_price['Close'] - pd_stock_price[st_min_columns_name]) * 100
        pd_stock_price[st_k_columns_name] = pd_stock_price[st_k_columns_name] / (
                    pd_stock_price[st_max_columns_name] - pd_stock_price[st_min_columns_name])

        st_d_columns_name = str('ST_D_') + str(period)
        pd_stock_price[st_d_columns_name] = pd_stock_price[st_k_columns_name].rolling(3).mean()

    return pd_stock_price

In [662]:
pd_price = get_stochastic_oscillator(pd_price, [5, 10, 20, 30])

In [663]:
def get_rate_of_price_change(pd_stock_price, period_of_list):

    for period in period_of_list:
        price_diff_columns_name = str('R_Price_diff_') + str(period)
        pd_stock_price[price_diff_columns_name] = pd_stock_price['Close'].diff(period - 1)

        price_shift_columns_name = str('R_Price_shift_') + str(period)
        pd_stock_price[price_shift_columns_name] = pd_stock_price['Close'].shift(period - 1)

        price_roc_columns_name = str('R_Price_ROPC_') + str(period)
        pd_stock_price[price_roc_columns_name] = pd_stock_price[price_diff_columns_name] / pd_stock_price[price_shift_columns_name]

    return pd_stock_price

In [664]:
pd_price = get_rate_of_price_change(pd_price, [5, 10, 20, 30])

In [665]:
def get_rate_of_volume_change(pd_stock_price, period_of_list):

    for period in period_of_list:
        price_diff_columns_name = str('R_Volume_diff_') + str(period)
        pd_stock_price[price_diff_columns_name] = pd_stock_price['Volume'].diff(period - 1)

        price_shift_columns_name = str('R_Volume_shift_') + str(period)
        pd_stock_price[price_shift_columns_name] = pd_stock_price['Volume'].shift(period - 1)

        price_roc_columns_name = str('R_Volume_ROPC_') + str(period)
        pd_stock_price[price_roc_columns_name] = pd_stock_price[price_diff_columns_name] / pd_stock_price[price_shift_columns_name]

    return pd_stock_price

In [666]:
pd_price = get_rate_of_price_change(pd_price, [5, 10, 20, 30])

In [667]:
def get_cci_index(pd_stock_price, period_of_list):

    for period in period_of_list:
        period_sma_columns_name = str('CCI_TP_SMA_') + str(period)
        pd_stock_price[period_sma_columns_name] = pd_stock_price['TP'].rolling(period, min_periods=period_of_list[0]).mean()

        period_mad_columns_name = str('CCI_TP_MAD_') + str(period)
        pd_stock_price[period_mad_columns_name] = pd_stock_price['TP'].rolling(period, min_periods=period_of_list[0]).apply(lambda x: pd.Series(x).mad())

        period_cci_columns_name = str('CCI_') + str(period)
        pd_stock_price[period_cci_columns_name] = (pd_stock_price['TP'] - pd_stock_price[period_sma_columns_name])
        pd_stock_price[period_cci_columns_name] = pd_stock_price[period_cci_columns_name] / (0.015 * pd_stock_price[period_mad_columns_name])

    return pd_stock_price

In [668]:
pd_price = get_cci_index(pd_price, [5, 10, 20, 30])

In [669]:
def get_adx_index(pd_stock_price, period_of_list):

    pd_stock_price['HL'] = pd_stock_price['High'] - pd_stock_price['Low']
    pd_stock_price['absHC'] = abs(pd_stock_price['High'] - pd_stock_price['Close'].shift(1))
    pd_stock_price['absLC'] = abs(pd_stock_price['Low'] - pd_stock_price['Close'].shift(1))
    pd_stock_price['TR'] = pd_stock_price[['HL', 'absHC', 'absLC']].max(axis=1)

    pd_stock_price['UpMove'] = pd_stock_price['High'] - pd_stock_price['High'].shift(1)
    pd_stock_price['DonwMove'] = pd_stock_price['Low'].shift(1) - pd_stock_price['Low']
    pd_stock_price['Zero'] = 0

    pd_stock_price['PlusDM'] = np.where((pd_stock_price['UpMove'] > pd_stock_price['DonwMove']) &
                                          (pd_stock_price['UpMove'] > pd_stock_price['Zero']),
                                          pd_stock_price['UpMove'], 0)
    pd_stock_price['MinusDM'] = np.where((pd_stock_price['UpMove'] < pd_stock_price['DonwMove']) &
                                           (pd_stock_price['DonwMove'] > pd_stock_price['Zero']),
                                           pd_stock_price['DonwMove'], 0)

    for period in period_of_list:

        atr_column_name = str('ATR_') + str(period)
        pd_stock_price[atr_column_name] = pd_stock_price['TR'].rolling(window=period, min_periods=period_of_list[0]).mean()

        natr_column_name = str('NATR_') + str(period)
        pd_stock_price[natr_column_name] = (pd_stock_price[atr_column_name] / pd_stock_price['Close']) * 100

        plus_di_column_name = str('plusDI_') + str(period)
        pd_plus_di_values = (pd_stock_price['PlusDM'] / pd_stock_price[atr_column_name])
        pd_stock_price[plus_di_column_name] = 100 * pd_plus_di_values.ewm(span=period, min_periods=0, adjust=True, ignore_na=False).mean()

        minus_di_column_name = str('MinusDI_') + str(period)
        pd_minus_di_values = (pd_stock_price['MinusDM'] / pd_stock_price[atr_column_name])
        pd_stock_price[minus_di_column_name] = 100 * pd_minus_di_values.ewm(span=period, min_periods=0, adjust=True, ignore_na=False).mean()

        adx_column_name = str('ADX_') + str(period)
        sub_plus_di_minus_di = (pd_stock_price[plus_di_column_name] - pd_stock_price[minus_di_column_name])
        add_plus_di_minus_di = (pd_stock_price[plus_di_column_name] + pd_stock_price[minus_di_column_name])

        pd_stock_price[adx_column_name] = 100 * (abs(sub_plus_di_minus_di / add_plus_di_minus_di)).ewm(span=period, min_periods=0, adjust=True, ignore_na=False).mean()

    return pd_stock_price

In [670]:
pd_price = get_adx_index(pd_price, [5, 10, 20, 30])

In [671]:
pd_price.head(30)

Date    Open    High  ...  plusDI_30  MinusDI_30      ADX_30
0   2020-01-06  647000  659000  ...        NaN         NaN         NaN
1   2020-01-07  652000  666000  ...        NaN         NaN         NaN
2   2020-01-08  644000  651000  ...        NaN         NaN         NaN
3   2020-01-09  636000  659000  ...        NaN         NaN         NaN
4   2020-01-10  650000  663000  ...  20.408163    0.000000  100.000000
5   2020-01-13  647000  663000  ...   9.863946    0.000000  100.000000
6   2020-01-14  658000  664000  ...   8.241199    0.000000  100.000000
7   2020-01-15  653000  668000  ...  11.968520    0.000000  100.000000
8   2020-01-16  669000  680000  ...  24.048172    0.000000  100.000000
9   2020-01-17  677000  685000  ...  24.777811    0.000000  100.000000
10  2020-01-20  671000  683000  ...  20.492327    4.828735   93.403427
11  2020-01-21  668000  673000  ...  17.294788   11.141057   82.205872
12  2020-01-22  660000  676000  ...  17.235938    9.548410   74.557277
13  2020-01-23  658000  664000  ...  14.951217   13.478896   65.360759
14  2020-01-28  649000  651000  ...  13.095604   29.886962   62.097224
15  2020-01-29  628000  632000  ...  11.561705   26.386279   59.399501
16  2020-01-30  626000  631000  ...  10.275165   29.106342   58.110681
17  2020-01-31  631000  637000  ...  12.748378   26.012186   55.570962
18  2020-02-03  624000  624000  ...  11.447520   26.234403   53.904668
19  2020-02-04  612000  620000  ...  10.321652   27.554822   53.077903
20  2020-02-05  614000  618000  ...   9.339735   24.933485   52.356847
21  2020-02-06  613000  637000  ...  18.295382   22.631982   48.502068
22  2020-02-07  624000  630000  ...  16.652275   20.599405   45.097712
23  2020-02-10  617000  624000  ...  15.193630   22.847571   42.909818
24  2020-02-11  627000  630000  ...  16.893421   20.891398   40.141868
25  2020-02-12  615000  625000  ...  15.476924   20.135143   37.872794
26  2020-02-13  621000  642000  ...  22.411802   18.478852   35.548609
27  2020-02-14  628000  640000  ...  20.600375   16.985305   33.452793
28  2020-02-17  634000  647000  ...  22.216938   15.634502   32.175371
29  2020-02-18  636000  661000  ...  26.792452   14.409515   32.009177

[30 rows x 124 columns]

In [672]:
pd_pivot_data = pd.pivot_table(data=pd_price, columns='weekday', index='weeknum')

In [673]:
pd_pivot_data = pd_pivot_data.ffill()
pd_pivot_data = pd_pivot_data.ffill(axis=1)

In [674]:
pd_pivot_data.shape

(99, 605)

In [675]:
pd_pivot_data = pd_pivot_data.dropna()

In [676]:
pd_pivot_data.shape

(98, 605)

In [677]:
pd_pivot_data.head(10)

ADX_10                          ... week_diff                  
weekday           0           1           2  ...         2        3        4
weeknum                                      ...                            
3        100.000000  100.000000  100.000000  ...    3000.0 -29000.0 -38000.0
4         88.355470   68.768771   57.103165  ...  -43000.0 -39000.0 -38000.0
5         88.355470   51.547226   53.803154  ...  -18000.0   2000.0  -4000.0
6         54.518164   55.865688   56.949631  ...   16000.0   5000.0  12000.0
7         35.722817   29.900388   24.955963  ...   28000.0  21000.0   8000.0
8         33.558153   39.604227   44.989594  ...  -48000.0 -47000.0 -48000.0
9         41.214994   39.880635   39.289218  ...  -35000.0 -24000.0 -30000.0
10        48.444468   53.147188   56.229402  ...  -48000.0 -78000.0 -66000.0
11        52.697568   53.012868   57.013656  ...  -71500.0 -97000.0 -60500.0
12        67.162871   67.220053   68.369363  ...   -3000.0  42000.0  25000.0

[10 rows x 605 columns]

In [678]:
pd_pivot_data['MACD'].head(10)

weekday              0              1  ...              3              4
weeknum                                ...                              
3        671000.000000  671000.000000  ...  671000.000000  671000.000000
4        671000.000000  671000.000000  ...  671000.000000  671000.000000
5        616000.000000  616000.000000  ...  616000.000000  616000.000000
6        620000.000000  620000.000000  ...  620000.000000  620000.000000
7        625000.000000   -8110.513198  ...   -6577.694929   -5466.611523
8         -3743.182713   -1555.392097  ...     927.205761    1069.475885
9         -1139.951838   -2929.535793  ...   -6114.066220   -7872.019089
10       -10603.770110  -13078.563028  ...  -15248.948169  -16607.459548
11       -18408.242664  -19994.845011  ...  -26615.681076  -29433.624248
12       -30445.256957  -32922.576827  ...  -43455.482178  -45377.422542

[10 rows x 5 columns]

In [679]:
stock_name = '영풍'
stock_code = '000670'

In [680]:
pd_pivot_data.to_csv(str('price/pivot_') + str(stock_code) + str('_price.csv'))

In [705]:
import tensorflow as tf

import keras

from keras import layers
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers import LSTM
from keras.layers import Dropout
from keras.models import model_from_json

from keras.layers import Input, Dense
from keras.models import Model

from keras.callbacks import ModelCheckpoint, EarlyStopping, CSVLogger

from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_absolute_error

In [682]:
def make_dataset(data, label, window_size=4):
    first_list = []
    second_list = []
    third_list = []
    forth_list = []

    label_list = []
    for i in range(len(data) - window_size):
        first_list.append(np.array(data.iloc[i]))
        second_list.append(np.array(data.iloc[i+1]))
        third_list.append(np.array(data.iloc[i+2]))
        forth_list.append(np.array(data.iloc[i+3]))
        label_list.append(np.array(label.iloc[i+window_size]))
    return np.array(first_list), np.array(second_list), np.array(third_list), np.array(forth_list), np.array(label_list)

In [683]:
def multi_input_ann_model(my_shape):
    # This returns a tensor
    # This returns a tensor
    input1 = Input(shape=my_shape)
    input2 = Input(shape=my_shape)
    input3 = Input(shape=my_shape)
    input4 = Input(shape=my_shape)

    # a layer instance is callable on a tensor, and returns a tensor
    first_input2 = Dense(10, activation='relu')(input1)
    first_output = Dense(5, activation='linear')(first_input2)

    second_input1 = layers.concatenate([first_output, input2])
    second_input2 = Dense(10, activation='relu')(second_input1)
    second_output = Dense(5, activation='linear')(second_input2)

    third_input1 = layers.concatenate([second_output, input3])
    third_input2 = Dense(10, activation='relu')(third_input1)
    third_output = Dense(5, activation='linear')(third_input2)

    forth_input1 = layers.concatenate([third_output, input4])
    forth_input2 = Dense(10, activation='relu')(forth_input1)
    forth_output = Dense(5, activation='linear')(forth_input2)

    # This creates a model that includes
    # the Input layer and three Dense layers
    model = Model(inputs=[input1, input2, input3, input4], outputs=forth_output)

    print(model.summary())

    return model

In [684]:
print(pd_price.head(10))
print(pd_price.tail(10))

         Date    Open    High     Low  ...   NATR_30  plusDI_30  MinusDI_30  ADX_30
0  2020-01-06  647000  659000  643000  ...       NaN        NaN         NaN     NaN
1  2020-01-07  652000  666000  647000  ...       NaN        NaN         NaN     NaN
2  2020-01-08  644000  651000  636000  ...       NaN        NaN         NaN     NaN
3  2020-01-09  636000  659000  636000  ...       NaN        NaN         NaN     NaN
4  2020-01-10  650000  663000  645000  ...  2.987805  20.408163         0.0   100.0
5  2020-01-13  647000  663000  646000  ...  2.912867   9.863946         0.0   100.0
6  2020-01-14  658000  664000  647000  ...  2.870189   8.241199         0.0   100.0
7  2020-01-15  653000  668000  653000  ...  2.759009  11.968520         0.0   100.0
8  2020-01-16  669000  680000  661000  ...  2.712418  24.048172         0.0   100.0
9  2020-01-17  677000  685000  671000  ...  2.682563  24.777811         0.0   100.0

[10 rows x 124 columns]
           Date    Open    High  ...  plusDI_30  Mi

In [685]:
select_columns = ['Close', 'Open', 'High', 'Low', 'week_diff']
select_columns = select_columns + ['SMA_5', 'SMA_10', 'SMA_20']
select_columns = select_columns + ['EMA_5', 'EMA_10', 'EMA_20']
select_columns = select_columns + ['ADX_5', 'ADX_10', 'ADX_20']
select_columns = select_columns + ['MFI_5', 'MFI_10', 'MFI_20']
select_columns = select_columns + ['OBV_5', 'OBV_10', 'OBV_20']
select_columns = select_columns + ['PVT_5', 'PVT_10', 'PVT_20']
select_columns = select_columns + ['CCI_5', 'CCI_10', 'CCI_20']
select_columns = select_columns + ['ST_K_5', 'ST_K_10', 'ST_K_20']
select_columns = select_columns + ['ST_D_5', 'ST_D_10', 'ST_D_20']
select_columns = select_columns + ['weekday', 'weeknum']

In [686]:
total_scaler = MinMaxScaler()
close_scaler = MinMaxScaler()

pd_select_data = pd_price.loc[:, pd_price.columns.isin(select_columns)]
#pd_select_data['Close'] = close_scaler.fit_transform(pd_select_data['Close'].to_numpy().reshape(-1, 1))
pd_select_data['week_diff'] = close_scaler.fit_transform(pd_select_data['week_diff'].to_numpy().reshape(-1, 1))

pd_scale_data = pd.DataFrame(total_scaler.fit_transform(pd_select_data), columns=pd_select_data.columns)

pd_pivot_data = pd.pivot_table(data=pd_scale_data, values=select_columns, columns='weekday', index='weeknum')

pd_pivot_data = pd_pivot_data.ffill()
pd_pivot_data = pd_pivot_data.ffill(axis=1)

print("-- pd_pivot_data.shape --")
print(pd_pivot_data.shape)

pd_pivot_data = pd_pivot_data.dropna()

print("-- pd_pivot_data.dropna() pd_pivot_data.shape --")
print(pd_pivot_data.shape)

# print(pd_pivot_data.head(10))
# print(pd_pivot_data.tail(10))

-- pd_pivot_data.shape --
(99, 160)
-- pd_pivot_data.dropna() pd_pivot_data.shape --
(98, 160)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [687]:
total_x1, total_x2, total_x3, total_x4, total_y = make_dataset(pd_pivot_data, pd_pivot_data['week_diff'], window_size=4)
print(" -- total_x.shape, total_y.shape -- ")
print(total_x1.shape, total_x2.shape, total_x3.shape, total_x4.shape, total_y.shape)

 -- total_x.shape, total_y.shape -- 
(94, 160) (94, 160) (94, 160) (94, 160) (94, 5)


In [688]:
print(total_y[0])

[0.65789474 0.71491228 0.67105263 0.64035088 0.58333333]


In [689]:
test_rate = 0.8

# train, test set 생성
train_x1 = total_x1[:int(total_x1.shape[0]*test_rate)]
train_x2 = total_x2[:int(total_x2.shape[0]*test_rate)]
train_x3 = total_x3[:int(total_x3.shape[0]*test_rate)]
train_x4 = total_x4[:int(total_x4.shape[0]*test_rate)]

test_x1 = total_x1[int(total_x1.shape[0]*test_rate):]
test_x2 = total_x2[int(total_x2.shape[0]*test_rate):]
test_x3 = total_x3[int(total_x3.shape[0]*test_rate):]
test_x4 = total_x4[int(total_x4.shape[0]*test_rate):]

# print(" -- train_x1, train_x2, train_x3, train_x4 -- ")
# print(train_x1[0], train_x2[0], train_x3[0], train_x4[0])

train_y = total_y[:int(total_y.shape[0]*test_rate)]
test_y = total_y[int(total_y.shape[0]*test_rate):]

In [690]:
# LEARNING_RATE = 0.005
LEARNING_RATE = 0.01
EPOCHS = 300
BATCH_SIZE = 30
SPLIT_RATE = 0.2

In [691]:
# 재현성을 위해서 설정하는 부분.
tf.random.set_seed(100)

my_model = multi_input_ann_model(pd_pivot_data.shape[1])

save_model_name = str("model/") + str(stock_code) + str("_ann_day_model.h5")
log_filename = str("log/") + str(stock_code) + str("_ann_day_model_log.txt")

es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=100)
mc = ModelCheckpoint(save_model_name, monitor='val_loss', mode='min', save_best_only=True)
log = CSVLogger(log_filename, append=False, separator=',')

adam = tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE)

my_model.compile(loss='mae', optimizer=adam, metrics=['mae'])

Model: "model_6"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_25 (InputLayer)          [(None, 160)]        0           []                               
                                                                                                  
 dense_48 (Dense)               (None, 10)           1610        ['input_25[0][0]']               
                                                                                                  
 dense_49 (Dense)               (None, 5)            55          ['dense_48[0][0]']               
                                                                                                  
 input_26 (InputLayer)          [(None, 160)]        0           []                               
                                                                                            

In [692]:
my_model.fit(x=[train_x1, train_x2, train_x3, train_x4], y=train_y, epochs=EPOCHS, batch_size=BATCH_SIZE, validation_split=SPLIT_RATE,
          callbacks=[log, mc])

Epoch 1/300
2/2 [==============================] - 1s 223ms/step - loss: 0.4189 - mae: 0.4189 - val_loss: 0.3481 - val_mae: 0.3481
Epoch 2/300
2/2 [==============================] - 0s 36ms/step - loss: 0.3673 - mae: 0.3673 - val_loss: 0.3693 - val_mae: 0.3693
Epoch 3/300
2/2 [==============================] - 0s 27ms/step - loss: 0.3442 - mae: 0.3442 - val_loss: 0.3660 - val_mae: 0.3660
Epoch 4/300
2/2 [==============================] - 0s 64ms/step - loss: 0.3305 - mae: 0.3305 - val_loss: 0.3386 - val_mae: 0.3386
Epoch 5/300
2/2 [==============================] - 0s 62ms/step - loss: 0.2987 - mae: 0.2987 - val_loss: 0.2953 - val_mae: 0.2953
Epoch 6/300
2/2 [==============================] - 0s 62ms/step - loss: 0.2799 - mae: 0.2799 - val_loss: 0.2789 - val_mae: 0.2789
Epoch 7/300
2/2 [==============================] - 0s 63ms/step - loss: 0.2495 - mae: 0.2495 - val_loss: 0.2520 - val_mae: 0.2520
Epoch 8/300
2/2 [==============================] - 0s 61ms/step - loss: 0.2425 - mae: 0.2

In [693]:
pred_test = my_model.predict(x=[test_x1, test_x2, test_x3, test_x4])

In [694]:
print(pred_test)

[[0.39755303 0.36523357 0.3616343  0.36833066 0.39742738]
 [0.38878402 0.3552461  0.35133144 0.3582065  0.38944316]
 [0.38236377 0.34793374 0.34378818 0.35079402 0.3835975 ]
 [0.5687946  0.56026936 0.5628289  0.56603616 0.5533432 ]
 [0.44139424 0.4151666  0.4131441  0.4189472  0.4373449 ]
 [0.42323452 0.39448357 0.3918079  0.39798105 0.42081046]
 [0.56563497 0.55667067 0.5591166  0.56238824 0.55046636]
 [0.3557646  0.3176386  0.3125364  0.3200842  0.3593789 ]
 [0.4256979  0.39728922 0.3947022  0.40082508 0.42305332]
 [0.42482102 0.39629048 0.39367193 0.3998127  0.42225495]
 [0.5982907  0.59386396 0.59748435 0.6000906  0.5801995 ]
 [0.3629916  0.3258698  0.32102752 0.3284281  0.3659591 ]
 [0.37745717 0.3423454  0.33802333 0.34512916 0.37913004]
 [0.36992782 0.3337698  0.329177   0.3364362  0.37227455]
 [0.40236312 0.37071204 0.3672858  0.37388414 0.40180698]
 [0.4434961  0.41440022 0.4265724  0.41745648 0.43169868]
 [0.49672404 0.47818452 0.47815198 0.48282772 0.4877228 ]
 [0.3727623  0

In [695]:
scaler_pred_test = close_scaler.inverse_transform(pred_test)

In [696]:
print(scaler_pred_test)

[[-34357.91   -41726.746  -42547.375  -41020.61   -34386.555 ]
 [-36357.242  -44003.89   -44896.43   -43328.914  -36206.957 ]
 [-37821.06   -45671.105  -46616.293  -45018.96   -37539.77  ]
 [  4685.1704   2741.413    3324.9888   4056.2456   1162.2444]
 [-24362.113  -30342.018  -30803.14   -29480.04   -25285.361 ]
 [-28502.527  -35057.746  -35667.793  -34260.32   -29055.213 ]
 [  3964.7722   1920.9117   2478.5852   3224.519     506.3298]
 [-43885.67   -52578.4    -53741.703  -52020.797  -43061.61  ]
 [-27940.88   -34418.06   -35007.9    -33611.88   -28543.842 ]
 [-28140.809  -34645.77   -35242.797  -33842.703  -28725.871 ]
 [ 11410.275   10400.984   11226.433   11820.662    7285.482 ]
 [-42237.914  -50701.684  -51805.727  -50118.395  -41561.32  ]
 [-38939.76   -46945.25   -47930.68   -46310.55   -38558.35  ]
 [-40656.453  -48900.484  -49947.645  -48292.543  -40121.402 ]
 [-33261.207  -40477.652  -41258.84   -39754.414  -33388.008 ]
 [-23882.889  -30516.748  -27741.49   -29819.922  -2657

In [697]:
scaler_test_y = close_scaler.inverse_transform(test_y)

In [698]:
print(scaler_test_y)

[[ 4.1000000e+04  2.8000000e+04  1.1000000e+04 -4.0000000e+03
  -2.2000000e+04]
 [-1.1000000e+04 -1.2000000e+04  2.5313085e-11  7.0000000e+03
  -2.0000000e+03]
 [-7.0000000e+03  3.0000000e+03 -2.0000000e+03 -3.0000000e+03
   9.0000000e+03]
 [-7.0000000e+03 -5.0000000e+03 -4.2000000e+04 -7.1000000e+04
  -3.9000000e+04]
 [-7.0000000e+03 -1.5000000e+04 -1.0000000e+04  6.0000000e+03
   4.7000000e+04]
 [ 4.3000000e+04  5.9000000e+04  8.4000000e+04  1.0300000e+05
   7.9000000e+04]
 [ 5.3000000e+04  2.2000000e+04 -1.8000000e+04 -4.6000000e+04
  -3.1000000e+04]
 [-1.1000000e+04 -6.0000000e+03 -4.0000000e+03  8.0000000e+03
  -1.0000000e+03]
 [-3.9000000e+04 -3.4000000e+04 -3.5000000e+04 -3.6000000e+04
  -4.6000000e+04]
 [-3.9000000e+04 -3.4000000e+04 -3.5000000e+04 -3.2000000e+04
  -5.7000000e+04]
 [-3.9000000e+04 -3.7000000e+04 -8.0000000e+03  1.0000000e+03
   4.7000000e+04]
 [-3.9000000e+04  4.0000000e+04  6.7000000e+04  5.8000000e+04
   7.2000000e+04]
 [-3.9000000e+04  4.2000000e+04  1.60000

In [710]:
for index in range(0, 10):
  print(scaler_test_y[index], scaler_pred_test[index], (scaler_test_y[index] - scaler_pred_test[index]))

[ 41000.  28000.  11000.  -4000. -22000.] [-34357.91  -41726.746 -42547.375 -41020.61  -34386.555] [75357.91015625 69726.74609375 53547.375      37020.609375
 12386.5546875 ]
[-1.1000000e+04 -1.2000000e+04  2.5313085e-11  7.0000000e+03
 -2.0000000e+03] [-36357.242 -44003.89  -44896.43  -43328.914 -36206.957] [25357.2421875  32003.890625   44896.4296875  50328.9140625
 34206.95703125]
[-7000.  3000. -2000. -3000.  9000.] [-37821.06  -45671.105 -46616.293 -45018.96  -37539.77 ] [30821.05859375 48671.10546875 44616.29296875 42018.9609375
 46539.76953125]
[ -7000.  -5000. -42000. -71000. -39000.] [4685.1704 2741.413  3324.9888 4056.2456 1162.2444] [-11685.17041016  -7741.41308594 -45324.98876953 -75056.24560547
 -40162.24438477]
[ -7000. -15000. -10000.   6000.  47000.] [-24362.113 -30342.018 -30803.14  -29480.04  -25285.361] [17362.11328125 15342.01757813 20803.140625   35480.0390625
 72285.36132813]
[ 43000.  59000.  84000. 103000.  79000.] [-28502.527 -35057.746 -35667.793 -34260.32  -2

In [711]:
print(mean_absolute_error(scaler_test_y, scaler_pred_test))

38272.891173352706
